plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 1 --freq --out 1
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 2 --freq --out 2
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 3 --freq --out 3
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 4 --freq --out 4
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 5 --freq --out 5
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 6 --freq --out 6
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 7 --freq --out 7
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 8 --freq --out 8
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 9 --freq --out 9
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 10 --freq --out 10
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 11 --freq --out 11
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 12 --freq --out 12
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 13 --freq --out 13
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 14 --freq --out 14
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 15 --freq --out 15
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 16 --freq --out 16
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 17 --freq --out 17
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 18 --freq --out 18
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 19 --freq --out 19
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 20 --freq --out 20
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 21 --freq --out 21
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 22 --freq --out 22
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 23 --freq --out 23
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 24 --freq --out 24
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 25 --freq --out 25
plink --bfile /dataE/AWIGenGWAS/plink/awigen/input/awigen --filter-males --thin 0.05 --chr 26 --freq --out 26
